#!/bin/bash

python2 /home/lars/Projects/type_erasure/emtypen/emtypen.py --form /home/lars/Projects/type_erasure/emtypen/forms/basic.hpp --clang-path /usr/lib/llvm-3.8/lib plain_interface.hh > interface.hh
